services:
  frontend:
    build:
      context: ./scdl-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./scdl-frontend/.env

  backend:
    build:
      context: ./scdl-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
